### ISSUE TITLE
user_recs returns recommendations that a user already knows

### ISSUE THREAD

**Issue by jcalem** [ankane/cmfrec-ruby#2]
Hello again,

In this example: 
```
[
  {user_id: 1, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 2, value: 1.0},
  {user_id: 2, item_id: 3, value: 0.0}
]
```
`recommender.user_recs(1, count: 3)` returns item 1 as the highest score even though it's value is already known.

Looks the same as this issue in the other library: https://github.com/ankane/disco/issues/6

**Comment by ankane** [comment]
Thanks @jcalem!

**Comment by jcalem** [comment]
I'm getting this error when running `recommender.fit`

```
Fiddle::DLError (dlopen(/Users/jcalem/.rvm/gems/ruby-2.6.3/bundler/gems/cmfrec/vendor/libcmfrec.dylib, 9): image not found)
```

**Comment by ankane** [comment]
I just pushed a new release you can use.

The shared libraries aren't included in the Git repo, so to use an unreleased version, you'll need to fork the gem, download the shared libraries (`bundle exec rake vendor:all`), update `.gitignore` so they can be committed, and then commit them to the fork.
