### ISSUE TITLE
Is there a setting to disable verbose output?

### ISSUE THREAD

**Issue by vitobotta** [ankane/cmfrec-ruby#4]
Hi! I see output like "Completed ALS iteration" and other stuff which is annoying in tests. Is it possible to disable it somehow? Thanks!

**Comment by ankane** [comment]
Hey @vitobotta, you can do:

```ruby
Cmfrec::Recommender.new(verbose: false)
```

**Comment by vitobotta** [comment]
Perfect, thanks!
