### ISSUE TITLE
[Question] Equal ratings/values vs different ones

### ISSUE THREAD

**Issue by vitobotta** [ankane/cmfrec-ruby#6]
Hi, I couldn't figure this out from looking at the code. Say I have 3 users A, B, C who all like item X. But A and B give X a rating of 5, while C gives X a rating of 3. Is my assumption correct that when recommending similar users to A, B should rank higher than C because they are more similar ratings to A's for the same items compared to C? Thanks!

**Comment by ankane** [comment]
Hi @vitobotta, unfortunately, I don't have the bandwidth to help with more questions about similar users.
